version : '3'
services:
  ############################
  # daprtestserviceone app + Dapr sidecar
  ############################
  daprtestserviceone:
    image: daprtestserviceone
    build:
      context: ./daprtestserviceone/
    ports:
      - "3500:3500"
      - "80:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      
  daprtestserviceone-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "daprtestserviceone",
    "-app-port", "80",
    "-components-path", "/components",
    "-log-level", "debug"]
    volumes:
      - "./components/components-docker/:/components"
    depends_on:
      - daprtestserviceone
    network_mode: "service:daprtestserviceone"
    restart: unless-stopped

  ############################
  # daprtestservicetwo app + Dapr sidecar
  ############################
  daprtestservicetwo:
    image: daprtestservicetwo
    build:
      context: ./daprtestservicetwo/
    ports:
      - "3501:3501"
      
  daprtestservicetwo-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "daprtestservicetwo",
    "-app-port", "80",
    "-components-path", "/components",
    "-log-level", "debug"]
    volumes:
      - "./components/components-docker/:/components"
    depends_on:
      - daprtestservicetwo
    network_mode: "service:daprtestservicetwo"
    restart: unless-stopped
    
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81