name: dapr
extensions:
  # Configuration for dapr goes here.
- name: dapr
  components-path: components

# Services to run go here.
services:
  
  # The name will be used as the app-id. For a .NET project, Tye only needs the path to the project file.
- name: daprtestclient
  project: daprtestclient/daprtestclient.csproj
- name: daprtestserver
  project: daprtestserver/daprtestserver.csproj
  tags:
    - server

  # Containers you want to run need an image name and set of ports to expose.
- name: redis
  image: redis
  bindings:
    - port: 6973
  tags: 
    - server
