apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
    - name: accessKey
      secretKeyRef:
        name: AWS.accessKey
        key: AWS.accessKey
    - name: secretKey
      secretKeyRef:
        name: AWS.secretKey
        key: AWS.secretKey
    - name: endpoint
      value: "http://localstack:4566" # Optional
    - name: region
      value: us-east-1

auth:
  secretStore: local-secret-store