apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.aws.dynamodb
  version: v1
  metadata:
  - name: table
    value: "statestore"
  - name: accessKey
    secretKeyRef:
        name: AWS.accessKey
        key: AWS.accessKey
  - name: secretKey
    secretKeyRef:
        name: AWS.secretKey
        key: AWS.secretKey
  - name: endpoint
    value: "http://localstack:4566" # Optional
  - name: region
    value: "us-east-1" # Optional

auth:
  secretStore: local-secret-store